### ISSUE TITLE
Página Productos (General)

### ISSUE THREAD

**Issue by carloscastromx** [carloscastromx/startoys#7]
Página de Productos donde se podrá filtrar por atributos como precio, marca, colección, etc.

**Comment by carloscastromx** [comment]
Falta que los productos cambien según el filtro pero puedes empezar ya con el diseño, ya está en Figma como debe quedar y ya puse las clases en los elementos para que solo agregues el CSS @AlejandroCastaneda52 

El archivo actualizado está aquí y en el servidor

**Comment by AlejandroCastaneda52** [comment]
listo, falta el botón

**Comment by carloscastromx** [comment]
Falta hacer los ajustes necesarios

**Comment by AlejandroCastaneda52** [comment]
listo
