### ISSUE TITLE
Diseño Responsivo

### ISSUE THREAD

**Issue by carloscastromx** [carloscastromx/startoys#8]
Uso de media queries en CSS para adaptación de los estilos a pantallas más pequeñas

**Comment by AlejandroCastaneda52** [comment]
Ya carlitos, mejor dime que no le sé :c

**Comment by AlejandroCastaneda52** [comment]
ya quedó falta que des el visto bueno

**Comment by carloscastromx** [comment]
Lo checo y te aviso 🌚
